const words = {
    'ok dude': "lav jan",
    "wholesale" : "biriq",
    "affordable": "matcheli",
    "discounted": "zexjvac",
    "reasonable": "xelqin mot",
    "favourable": "jebi gyora",
    "one-of-a-kind": "chkrknvox",
    "eco-friendly": "ekologiapes maqur",
    "high-end": "bardzrorak",
    "tracking": "hetevel, check anel, nayel",
    "shipping": "araqum, poxadrum",
    "goods": "apranq",
    "impulse buys": "chnaxatesvac gnumner",
    "compared": "hamematel",
    "overpay": "gercaxs, avel vcharel",
    'get closer': 'motenal',
    'hundreds ': 'haryuravor',
    'through ': 'mijov',
    'looked after': 'xnamel',
    'As well as': 'nayev',
    'Although': 'chnayac',
    'quite ': 'bavakanin',
    'berries': 'hataptuxner',
    'I am not familiar with these dishes.': 'es canot chem ays ustestnerin',
    'We can share them with each other': 'menq karox enq ayn kisel amen mekis mej',
    'draft beer': 'lcnovi garejur',
    'semi-dry': 'kisachor',
    'I was joking': 'es katakum ei',
    'insisting': 'pndel, hamozel',
    'bitter': 'dary',
    'The double is going to be very strong.': 'doubley shat tund e linelu',
    'complimentary': 'hyurasirutyun',
    'It was very nice to try it.': 'shat urax ei pordzel ayn',
    "it's up to you": 'duq eq voroshum, ayn dzezanic e kaxvac',
    'invoice': 'hdm, check',
    'Yes, we will definately come back.': 'ayo menq hastat kganq het',
    "bring down": "gin qcel",
    "aim": "npatak",
    "queue": "hert",
    "sell out": "sparel",
    "pop into the store": "arag mtnem xanut dus gam",
    "set me back": "vres esqan nstav",
    "Splash out": "aranc hashvelu azatoren caxsel",
    "Is this on sale?": "sa vacharvum e",
    "deal": "gorcarq",
    "It is not worth buying, I am afraid.": "vaxenam charji da gnel",
    "offer": 'arajarkel',
    "rude": "kopit",
    "stolen": "goxanal",
    "It's really worth notifying": "arje texekacnel",
    "tip": "zgushacum, texekacnel, hushel",
    "purchases":"gnumner",
    "relatives": "harazatner",
    "antique": "hnavoch",
    "sunrise": "arevacag",
    "receipt": "andoragir",
    "bargain": "gorcarq",
    "department store": "hanraxanut",
    "shop assistant": "vacharox",
    "hiking": 'zbosnel',
    "biking": 'hecaniv qshel',
    "scuba diving": 'suzvel jury vonc kargna balonov banov',
    "abroad": "urish erkraci",
    "magnificent": 'tpavorich, hoyakap',
    "superb": 'tpavorich, hoyakap',
    "trendy": "vochayin",
    "boot": 'bagajnik',
    "bed and breakfast": 'naxachash ev mahchakal pracice',
    "corridor": 'aranq, mijancq',
    "elevator": 'lift',
    'hop-on hop-off': 'angliayi avtobusnery en karmir kinoneri avtobusy',
    "snorkeling": 'miayn aknocnerov ijnel jri tak, loxal, suzvel',
    "glasses": "aknoc",
    "sunglasses": "arevayin aknoc",
    "high boots": "kabluk",
    "jeans jacket": "jinsic jaket",
    "shoes": "koshik",
    "handbag": "payusak",
    "shirt": "sarochka",
    "leather jacket": "kojic kurtka",
    "shorts": "shortikner",
    "jumper": "gorcvac svitr",
    "mountain": "ler, sar",
    "expect": "aknkalel",
    "strange": "ancanot",
    "complain": "boxoqel",
    "refund": "poxhatucum",
    "nature": "bnutyun",
    "moon": "lusin",
    "pet": "yntani kendani",
    "ocean": "ovkianoc",
    "forest": "antar",
    "hat": "glxrk",
    "entertainment venues": "jamanci vayrer",
    "enjoy your stay"     : "vayeleq dzer hangisty",
    "don't mention it"    : "karox eq chnshel ayn",
    "attractions": "tesarjan vayrer, atrakcionner",
    "adventures" : "Հետաքրքրաշարժ",
    "probably"   : "havanabar",
    "recommend"  : "xorurd tal",
    "exciting"   : "huzich",
    "safely" : "apahove kerpov",
    "trip"   : 'champordutyun',
    "cab"    : "taxi",
    "subway" : "metro",
    "it sounds interesting": "hetaqrqir e hnchum",
    "endless": "anverj",
    "credibility": 'vstahutyun',
    "miserable": "թշվառ, խեղճ",
    "diversity": 'bazmazanutyun, tarber',
    "belt": "goti",
    "desert": "anapat",
    "since"  : "վաղուց", 
    "gate"   : "darpas",
    "scrumptious": "hamex", 
    "alleys": 'poxoci ancum', 
    "exceptional": "bacarik",
    "trolley": "dzernasaylak",
    "canoeing"   : "navarkutyun", 
    "hesitate"   : "tatanvel, erkmtel",
    "spectacular": 'tpavorich, hoyakap',
    "settle" : "kargavorel, glux berel",
    "direct" : "uxix, anmijakan, pryamo",
    "blame": "mexadrel",
    "carriage": 'vagon',
    "railway": 'poezi gic',
    "underground": 'getni tak',
    "land": 'ժամանել',
    "reclaim": "վերադարձնել",
    "abandon": "hrajarvel",
    "ability": "karoxutyun, yndunakutyun",
    "above": "ver, aveli qan",
    "abuse": 'charashahel',
    "among": "sharqum, mejnery",
    "essential": "eakan, himnakan",
    "unidirectional": "miakoxmani",
    "who we drifted apart with.": "ում հետ մենք բաժանվեցինք",
    "therapist": "թերապևտ",
    "terminal cancer": "վերջնական քաղցկեղ",
    "it really brought us closer together": "այն իսկապես մեզ ավելի մտերմացրեց:",
    "shoulder": "ուս",
    "are you still in touch with her": "դու դեռ կապի մեջ ես նրա հետ",
    "nevertheless": 'այնուամենայնիվ',
    "It was my brother's birthday and he blew his candles": 'axpors cnundn er momery pchec',
    "May I have your special attention, please?": 'xndrum em dzer hatuk ushadrutyuny',
    "Could you read the safety instructions?":    'karox eq kardal anvtangutyan hrahangnery?',
    "Could you make sure that it's correct?":     'karox eq vstah linel vor da chisht e?',
    "Could you put it underneath the seat?":      'karox eq dnel nstarani tak',
    "No, you can't do it, it's prohibited":       'voch, duq cheq karox anel da, argelvac e',
    "pull the door tight": 'qasheq dury amur',
    "blow": 'pchel',
    "pocket":     'grpan',
    "falling": "ընկնելը",
    "tears": "արցունքներ",
    "silent":  "լուռ",
    "there is no sight of light": "չկա լույսի տեսարան",
    "stone": "քար",
    "flame": 'բոց',
    "lips": "շուրթերը",
    "desire": "կիրք, ցանկություն",
    "something eats me": "ինչ-որ բան ուտում է ինձ, տանջում է ինձ",
    "upset": "վրդովված, անկարգություն",
    "faith": 'հավատք',
    "doubt": "կասկած",
    "regret": "զղջալ",
    "repair": "վերանորոգել",
    "what is going on": "ինչ է կատարվում",
    "sober": 'սթափ',
    "I take back what I said": 'Ես հետ եմ վերցնում ասածս',
    "you and I we're over": 'ես և դու վերջացրինք',
    "fault": "մեղքով",
};


module.exports = words;